
[[redirects]]
  from = "/api-weather/*"
  to = "https://api.openweathermap.org/data/2.5/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-plantid/*"
  to = "https://api.plant.id/v3/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-openrouter/*"
  to = "https://openrouter.ai/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-backend/*"
  to = "https://greeni-app-despliefuefinal.onrender.com/:splat"
  status = 200
  force = true
